import { KEYS, readAll, writeAll, writeOne, makeId, nowISO } from "./storage";
import { BOOKING_STATUS } from "./constants";

const DEMO_PASSWORD = "Demo@123";

export function seedIfNeeded() {
  if (localStorage.getItem(KEYS.SEEDED)) return;

  const users = [
    {
      id: "u_customer_demo",
      role: "customer",
      name: "Aanya Sharma",
      email: "customer@demo.com",
      password: DEMO_PASSWORD,
      phone: "9876500001",
      address: "12 MG Road, Bengaluru, Karnataka",
      avatar: "",
      createdAt: nowISO(),
    },
    {
      id: "p_rahul",
      role: "provider",
      name: "Rahul Verma",
      email: "rahul.electric@demo.com",
      password: DEMO_PASSWORD,
      phone: "9876500002",
      category: "electrician",
      bio: "Licensed electrician with 8 years of experience in residential wiring, fan & light installation, and panel upgrades.",
      experience: 8,
      serviceArea: "Koramangala, HSR Layout, BTM Layout",
      certifications: ["ITI Electrician Trade Certificate"],
      portfolio: [],
      createdAt: nowISO(),
    },
    {
      id: "p_priya",
      role: "provider",
      name: "Priya Nair",
      email: "priya.cleans@demo.com",
      password: DEMO_PASSWORD,
      phone: "9876500003",
      category: "cleaning",
      bio: "Professional deep-cleaning specialist for homes and offices. Eco-friendly products, careful with your belongings.",
      experience: 5,
      serviceArea: "Indiranagar, Whitefield",
      certifications: [],
      portfolio: [],
      createdAt: nowISO(),
    },
    {
      id: "p_imran",
      role: "provider",
      name: "Imran Sheikh",
      email: "imran.plumb@demo.com",
      password: DEMO_PASSWORD,
      phone: "9876500004",
      category: "plumber",
      bio: "Plumbing expert handling leak repairs, bathroom fittings, and pipeline installation.",
      experience: 10,
      serviceArea: "Jayanagar, JP Nagar",
      certifications: ["Govt. Certified Plumber"],
      portfolio: [],
      createdAt: nowISO(),
    },
    {
      id: "p_karan",
      role: "provider",
      name: "Karan Mehta",
      email: "karan.ac@demo.com",
      password: DEMO_PASSWORD,
      phone: "9876500005",
      category: "ac-repair",
      bio: "AC technician specializing in installation, gas refilling, and annual maintenance contracts.",
      experience: 6,
      serviceArea: "Marathahalli, Bellandur",
      certifications: ["Daikin Certified Technician"],
      portfolio: [],
      createdAt: nowISO(),
    },
    {
      id: "p_sunita",
      role: "provider",
      name: "Sunita Rao",
      email: "sunita.paint@demo.com",
      password: DEMO_PASSWORD,
      phone: "9876500006",
      category: "painter",
      bio: "Interior & exterior painting with texture and waterproofing finishes.",
      experience: 7,
      serviceArea: "Malleshwaram, Rajajinagar",
      certifications: [],
      portfolio: [],
      createdAt: nowISO(),
    },
  ];

  const services = [
    {
      id: "s_rahul_1",
      providerId: "p_rahul",
      name: "Switchboard & Wiring Repair",
      description:
        "Fault detection, switchboard replacement, and safe re-wiring for homes and apartments.",
      category: "electrician",
      price: 349,
      priceUnit: "visit",
      availability: "Mon–Sat, 8 AM – 8 PM",
      serviceArea: "Koramangala, HSR Layout, BTM Layout",
      active: true,
      createdAt: nowISO(),
    },
    {
      id: "s_rahul_2",
      providerId: "p_rahul",
      name: "Ceiling Fan Installation",
      description: "Installation or replacement of ceiling fans, including balancing and testing.",
      category: "electrician",
      price: 249,
      priceUnit: "fan",
      availability: "Mon–Sat, 8 AM – 8 PM",
      serviceArea: "Koramangala, HSR Layout, BTM Layout",
      active: true,
      createdAt: nowISO(),
    },
    {
      id: "s_priya_1",
      providerId: "p_priya",
      name: "Full Home Deep Cleaning",
      description: "Kitchen, bathroom, and living area deep clean with sanitisation.",
      category: "cleaning",
      price: 1499,
      priceUnit: "visit",
      availability: "Mon–Sun, 7 AM – 9 PM",
      serviceArea: "Indiranagar, Whitefield",
      active: true,
      createdAt: nowISO(),
    },
    {
      id: "s_imran_1",
      providerId: "p_imran",
      name: "Leak Detection & Pipe Repair",
      description: "Diagnose and fix leaking pipes, taps, and bathroom fittings.",
      category: "plumber",
      price: 299,
      priceUnit: "visit",
      availability: "Mon–Sat, 9 AM – 7 PM",
      serviceArea: "Jayanagar, JP Nagar",
      active: true,
      createdAt: nowISO(),
    },
    {
      id: "s_karan_1",
      providerId: "p_karan",
      name: "AC Service & Gas Refill",
      description: "Complete AC servicing with gas top-up and filter cleaning.",
      category: "ac-repair",
      price: 599,
      priceUnit: "unit",
      availability: "Mon–Sun, 9 AM – 8 PM",
      serviceArea: "Marathahalli, Bellandur",
      active: true,
      createdAt: nowISO(),
    },
    {
      id: "s_sunita_1",
      providerId: "p_sunita",
      name: "Interior Wall Painting",
      description: "Two-coat emulsion painting with surface prep and putty work.",
      category: "painter",
      price: 18,
      priceUnit: "sq.ft",
      availability: "Mon–Sat, 9 AM – 6 PM",
      serviceArea: "Malleshwaram, Rajajinagar",
      active: true,
      createdAt: nowISO(),
    },
  ];

  const bookings = [
    {
      id: "b_demo_completed",
      customerId: "u_customer_demo",
      providerId: "p_rahul",
      serviceId: "s_rahul_1",
      serviceName: "Switchboard & Wiring Repair",
      category: "electrician",
      date: "2026-06-10",
      time: "11:00 AM",
      address: "12 MG Road, Bengaluru, Karnataka",
      notes: "Two switchboards in living room need replacement.",
      price: 349,
      status: BOOKING_STATUS.COMPLETED,
      createdAt: "2026-06-05T10:00:00.000Z",
      updatedAt: "2026-06-10T13:00:00.000Z",
      rescheduleHistory: [],
      cancellation: null,
      payment: {
        status: "Paid",
        method: "UPI",
        transactionId: "TXN" + Math.floor(Math.random() * 1e9),
        amount: 349,
        date: "2026-06-05T10:20:00.000Z",
      },
      reviewed: true,
    },
    {
      id: "b_demo_confirmed",
      customerId: "u_customer_demo",
      providerId: "p_imran",
      serviceId: "s_imran_1",
      serviceName: "Leak Detection & Pipe Repair",
      category: "plumber",
      date: "2026-06-25",
      time: "03:00 PM",
      address: "12 MG Road, Bengaluru, Karnataka",
      notes: "Kitchen sink pipe is leaking.",
      price: 299,
      status: BOOKING_STATUS.CONFIRMED,
      createdAt: "2026-06-18T09:00:00.000Z",
      updatedAt: "2026-06-18T09:40:00.000Z",
      rescheduleHistory: [],
      cancellation: null,
      payment: {
        status: "Paid",
        method: "Credit Card",
        transactionId: "TXN" + Math.floor(Math.random() * 1e9),
        amount: 299,
        date: "2026-06-18T09:40:00.000Z",
      },
      reviewed: false,
    },
    {
      id: "b_demo_pending",
      customerId: "u_customer_demo",
      providerId: "p_priya",
      serviceId: "s_priya_1",
      serviceName: "Full Home Deep Cleaning",
      category: "cleaning",
      date: "2026-06-28",
      time: "10:00 AM",
      address: "12 MG Road, Bengaluru, Karnataka",
      notes: "",
      price: 1499,
      status: BOOKING_STATUS.PENDING,
      createdAt: "2026-06-20T08:00:00.000Z",
      updatedAt: "2026-06-20T08:00:00.000Z",
      rescheduleHistory: [],
      cancellation: null,
      payment: null,
      reviewed: false,
    },
  ];

  const reviews = [
    {
      id: "r_demo_1",
      bookingId: "b_demo_completed",
      customerId: "u_customer_demo",
      providerId: "p_rahul",
      rating: 5,
      comment: "Quick, clean work and arrived on time. Highly recommend!",
      createdAt: "2026-06-10T14:00:00.000Z",
    },
    {
      id: "r_seed_2",
      bookingId: "seed_only",
      customerId: "seed_user",
      providerId: "p_rahul",
      rating: 4,
      comment: "Good service, slightly delayed but fixed the issue properly.",
      createdAt: "2026-05-20T10:00:00.000Z",
    },
    {
      id: "r_seed_3",
      bookingId: "seed_only",
      customerId: "seed_user",
      providerId: "p_priya",
      rating: 5,
      comment: "House looked spotless after the visit. Will book again.",
      createdAt: "2026-05-15T10:00:00.000Z",
    },
    {
      id: "r_seed_4",
      bookingId: "seed_only",
      customerId: "seed_user",
      providerId: "p_imran",
      rating: 4,
      comment: "Fixed the leak fast, fair pricing.",
      createdAt: "2026-05-10T10:00:00.000Z",
    },
    {
      id: "r_seed_5",
      bookingId: "seed_only",
      customerId: "seed_user",
      providerId: "p_karan",
      rating: 5,
      comment: "AC is cooling like new. Very professional.",
      createdAt: "2026-05-08T10:00:00.000Z",
    },
    {
      id: "r_seed_6",
      bookingId: "seed_only",
      customerId: "seed_user",
      providerId: "p_sunita",
      rating: 4,
      comment: "Neat painting work, finished on schedule.",
      createdAt: "2026-05-02T10:00:00.000Z",
    },
  ];

  const notifications = [
    {
      id: makeId("ntf"),
      userId: "u_customer_demo",
      role: "customer",
      type: "Payment Successful",
      message: "Your payment of ₹349 for Switchboard & Wiring Repair was successful.",
      bookingId: "b_demo_completed",
      read: true,
      createdAt: "2026-06-05T10:20:00.000Z",
    },
    {
      id: makeId("ntf"),
      userId: "u_customer_demo",
      role: "customer",
      type: "Service Completed",
      message: "Rahul Verma marked your Switchboard & Wiring Repair as completed.",
      bookingId: "b_demo_completed",
      read: true,
      createdAt: "2026-06-10T13:00:00.000Z",
    },
    {
      id: makeId("ntf"),
      userId: "p_priya",
      role: "provider",
      type: "New Booking Request",
      message: "Aanya Sharma requested Full Home Deep Cleaning on 2026-06-28.",
      bookingId: "b_demo_pending",
      read: false,
      createdAt: "2026-06-20T08:00:00.000Z",
    },
  ];

  writeAll(KEYS.USERS, users);
  writeAll(KEYS.SERVICES, services);
  writeAll(KEYS.BOOKINGS, bookings);
  writeAll(KEYS.REVIEWS, reviews);
  writeAll(KEYS.NOTIFICATIONS, notifications);
  localStorage.setItem(KEYS.SEEDED, "true");
}

export const DEMO_ACCOUNTS = {
  customer: { email: "customer@demo.com", password: DEMO_PASSWORD },
  provider: { email: "rahul.electric@demo.com", password: DEMO_PASSWORD },
};
